# Generated by Django 2.2.4 on 2019-08-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='分类名称')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='手账和壁纸的分开类型')),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
                ('sign', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人发布的签名')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人图像')),
                ('date', models.DateField(auto_now_add=True, verbose_name='用户创建时间')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='用户电话号码')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='上传的地址')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='图片的分类')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片的描述')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='图片上传时间')),
                ('del_date', models.DateField(blank=True, null=True, verbose_name='图片删除时间')),
                ('is_delete', models.IntegerField(blank=True, null=True, verbose_name='是否删除，判断图片是否可见')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.User', verbose_name='用户信息')),
            ],
            options={
                'db_table': 'user_img',
            },
        ),
        migrations.CreateModel(
            name='Mural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片位置')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Style', verbose_name='壁纸分类')),
            ],
            options={
                'db_table': 'mural',
            },
        ),
        migrations.CreateModel(
            name='LikePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_fk', to='App.User', verbose_name='被喜欢的用户')),
                ('user_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_like_fk', to='App.User', verbose_name='喜欢的用户')),
            ],
            options={
                'db_table': 'like_person',
            },
        ),
        migrations.CreateModel(
            name='LikeMural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='用户收藏的时间')),
                ('mural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Mural', verbose_name='壁纸表')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'like_mural',
            },
        ),
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='手账的地址')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='手账价格')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='手账上传时间')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Style', verbose_name='手账分类')),
            ],
            options={
                'db_table': 'handbook',
            },
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='关注时间')),
                ('fans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fans_fk', to='App.User', verbose_name='粉丝')),
                ('followers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers_fk', to='App.User', verbose_name='关注')),
            ],
            options={
                'db_table': 'concern',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('handbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Handbook', verbose_name='手账')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'buy',
            },
        ),
    ]
