# Generated by Django 2.2.4 on 2019-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='更换昵称', max_length=20, null=True, verbose_name='昵称'),
        ),
    ]
